ibeer:
  build: .
  command: npm start
  expose:
    - 9200
  links:
    - redis:redis
    - mongo:mongo

nginx:
  restart: always
  build: ./resources/nginx/
  ports:
    - "80:80"
  links:
    - ibeer:ibeer

redis:
  image: redis

mongo:
  restart: always
  image : mongo:latest
  volumes_from:
    - mongodata

mongodata:
  image: busybox
  volumes:
    - /data/db


